import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import type { ReactNode } from 'react'

import { Header } from '@/components/header'
import { cn } from '@/lib/utils'

const font = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Log in | Mozaic',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'bg-background relative mx-auto min-h-screen w-full scroll-smooth antialiased',
          font.className,
        )}
      >
        <main>
          <Header />
          {children}
        </main>
      </body>
    </html>
  )
}
