import './globals.css'

import type { Metadata } from 'next'
// eslint-disable-next-line camelcase
import { Plus_Jakarta_Sans } from 'next/font/google'
import Image from 'next/image'
import type { ReactNode } from 'react'

import gridBackground from '@/assets/grid-background.svg'

const font = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Log in | Mozaic',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="w-full min-h-screen overflow-x-hidden bg-white relative">
          <Image
            src={gridBackground}
            alt=""
            layout="fill"
            objectFit="cover"
            className="hidden sm:block !top-[-150px]"
          />

          <div className="max-w-md my-0 sm:my-20 mx-auto bg-white sm:border sm:border-porcelain-100 sm:shadow-sm relative z-5 rounded-3xl">
            <div className="w-full flex flex-col px-6 sm:px-8 py-12">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
